//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouCantSpell.ReSharper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouCantSpell.ReSharper.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;{0}&quot; to dictionary.
        /// </summary>
        internal static string RS_AddToDictionaryText {
            get {
                return ResourceManager.GetString("RS_AddToDictionaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore spelling for &quot;{0}&quot;.
        /// </summary>
        internal static string RS_AddToIgnoreList {
            get {
                return ResourceManager.GetString("RS_AddToIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with: {0}.
        /// </summary>
        internal static string RS_ReplaceWith {
            get {
                return ResourceManager.GetString("RS_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling error: {0}.
        /// </summary>
        internal static string RS_SpellingErrorTip {
            get {
                return ResourceManager.GetString("RS_SpellingErrorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Fixes.
        /// </summary>
        internal static string RS_SpellingFixesCategoryName {
            get {
                return ResourceManager.GetString("RS_SpellingFixesCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Words.
        /// </summary>
        internal static string UI_IgnoredWordListTitle {
            get {
                return ResourceManager.GetString("UI_IgnoredWordListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dictionary.
        /// </summary>
        internal static string UI_UserDictionaryListTitle {
            get {
                return ResourceManager.GetString("UI_UserDictionaryListTitle", resourceCulture);
            }
        }
    }
}
